export const SET_NEW_FLYING_CARPET_ATTACHED = 'flyingCarpetOwner/SET_NEW_FLYING_CARPET_ATTACHED';
export const SET_FLYING_CARPET_TOKEN = 'flyingCarpetOwner/SET_FLYING_CARPET_TOKEN';
export const SET_FLYING_CARPET_ADDRESS = 'flyingCarpetOwner/SET_FLYING_CARPET_ADDRESS';
export const SET_CHANNEL_DATA = 'flyingCarpetOwner/SET_CHANNEL_DATA';
